DROP DATABASE IF EXISTS haystack_db;
CREATE DATABASE haystack_db;

-- move into the database
\c haystack_db

CREATE TABLE IF NOT EXISTS location
(
    loc_id         text PRIMARY KEY,
    loc_type       text NOT NULL,
    loc_name_en    text NOT NULL,
    loc_name_de    text NOT NULL,
    loc_hint_en    text NOT NULL,
    loc_hint_de    text NOT NULL,
    loc_info_en    text NOT NULL,
    loc_info_de    text NOT NULL
);

ALTER TABLE location OWNER to haystack_user;

CREATE TABLE IF NOT EXISTS collection
(
    collect_id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_name_en     text NOT NULL,
    collect_name_en     text NOT NULL,
    collect_group_en    text NOT NULL,
    collect_group_de    text NOT NULL,
    collect_info_en     text NOT NULL,
    collect_info_de     text NOT NULL
);

ALTER TABLE collection OWNER to haystack_user;

CREATE TABLE IF NOT EXISTS location_collection
(
  loc_id        text REFERENCES location (loc_id) ON UPDATE CASCADE,
  collect_id    int REFERENCES collection (collect_id) ON UPDATE CASCADE,
  CONSTRAINT location_collection_pkey PRIMARY KEY (loc_id, collect_id) -- explicit pk
);

ALTER TABLE location_collection OWNER to haystack_user;